### ISSUE TITLE
pacman-key can't import holo key

### ISSUE THREAD

**Issue by laerling** [majewsky/holo-pacman-repo#2]
### Steps to reproduce
Run `sudo pacman-key -r 0xF7A9C9DC4631BD1A`, like written in the [installation manual](http://holocm.org/install.html).

### Expected behavior
The key is successfully imported.

### Observed behavior
pacman-key outputs the following error:
```
gpg: error reading key: No public key
==> ERROR: The fingerprint of a specified key could not be determined.
```

### notes
This also appears when running `sudo pacman -Syu` and blocks the upgrade.

**Comment by majewsky** [comment]
Cannot reproduce. I did `sudo pacman-key -d 0xF7A9C9DC4631BD1A && sudo pacman -S holo-build`. Since the first command deleted the key, pacman prompted for a redownload of the key which succeeded. Same with `pacman-key -r` instead of `pacman -S`.

**Comment by laerling** [comment]
`sudo pacman-key -d 0xF7A9C9DC4631BD1A` yields `==> ERROR: The key identified by 0xF7A9C9DC4631BD1A could not be found locally.`

Furthermore I tried to no avail:
- Reinitializing and repopulating the archlinux keyring as described [here](https://www.archlinux.org/news/gnupg-21-and-the-pacman-keyring/)
- Reinstalling archlinux-keyring as described [here](https://bbs.archlinux.org/viewtopic.php?id=191279).

I will look a bit more into it later.

**Comment by majewsky** [comment]
This gave me the kick in the butt to finally add a keyring package to the repo. Can you please try downloading and installing https://repo.holocm.org/archlinux/x86_64/holo-keyring-20201009.1-1-any.pkg.tar.xz manually? To establish the trust chain, check for SHA256 `dec378054732fad0109eeff5da3933cefb70eaeb14217f20a33510f3772aea95`.

If this works for you, I'll adjust the website to make this the preferred installation method.

**Comment by laerling** [comment]
Worked for me :+1: 
I'm closing this now. You can reopen this ticket if you want to use it for tracking your website adjustment ;)
